language: node_js
node_js: lts/*
install: true
script:
- echo $REACT_APP_FIREBASE_KEY
- npm run build
notifications:
  email:
  - muatasimqazi@gmail.com
branches:
  only:
  - master
  - develop
deploy:
  - provider: firebase
    token:
      secure: "1/jXarLqwLzlaBy83j2IKV4522XfDRlakCNoF0ECeYuhY"
    project: "balochistan-encyclopedia"
    message: "deploying to production"
    on:
      branch: master
    skip_cleanup: true