language: node_js
node_js: lts/*
install: true
script:
- echo $REACT_APP_FIREBASE_KEY
- npm run build
notifications:
  email:
  - muatasimqazi@gmail.com
branches:
  only:
  - master
  - develop
deploy:
  - provider: firebase
    token:
      secure: "1/jXarLqwLzlaBy83j2IKV4522XfDRlakCNoF0ECeYuhY"
    project: "default"
    message: "deploying to production"
    on:
      branch: master
    skip_cleanup: true
env:
  global:
  - secure: Hh+xS1HecV85sDfSAU0/fN7Ns6HAOlIrByOcZHFMeyVBkUnhXE6RNuTPwc7jXnXgk7Q0wps6MLvMwMB+3dgSCdm5mPZmR3ydckAJvF5ZyvUIHms7X4tL/mZMdEC/zGkC3Yzj11HyYbl2/0fW4x55Du4a2VlbtEvw/zNiCUIWcUO7B373Efkgx9noBKLS4736oOIceyVdJTZbwA+6j7NYzvzcwj/fXO2PC2AgQMjuku6tsTIACN4gXlEtb0xjxAkBKy5e+XPIaHzyT3Ijetjs5OQraG/CjBTpXVLDdw+M5qJiPyu3HE+oHFDSkoGIhoz4nNZC2cAqaafmyA2oA04OzcvHnc0WXes64C4/7vrgF8BQ1+m9O8jHP36xe+O49hEIAWhtilEsSU4ad7TRvRawTTr4+HHy6VROlVCUYerscFJiGyOvX4qgNtSLmvaOJuKpC0FqgX4GQokeEdeyjT09+WwpoNU5+vV3SfJ6yHAD2LxBHUfGZsfbCwtIhuYpFcgkV62Kdmd0aRU8wrIlnoRimcTCchUckDqruVK08g1YYzO1SGT2n/UgjeJk7ehqLQWVACVRyi4L8xt/btpRYg7VYLUk2sK+3Okq3OEhzC9/YinZtEG70nqZy3hZPX+L3KiwODR3tOAIrLvKdfJSVh3C3CLDg/o9q3RYgqrbQfIOetQ=
  - secure: qeVCWNlAyxJ2RFWxi7dy6DT0QgNB7FAuxLvecw4h93INvsQnNWKhjikLwkq/xyoeI9Co9sXjbUuR0P9Z4/XzQP6YUmb8/nO8OgwrRTaw8yUDGNSGFblKto1kthbYFxMnQjq/SwnigxCpvXI11pjMURurNxKNX0yrd9VPeIyHruGnk+0layUrNmuj0TZ8ObTjHnXboSqbzJmzYcOxwEUuVkH35aqz2xCowhN+X114xDlWA1LTxl+j50XJ10KpBZA06AxsabOoX/IBq7njo3cyrAgHemcSddmjHx6qhQ8dE4AFPeLpdQd2Q87oLzbfkTqGRK4taO2bzrZhr7lAhk8HFzjR9k5RZpxLJSr8XHCULzMtYMS105uNBGN1fusP9Q8pbHIn/SokAM3CidQJHQrBZeS20zm3LkatL/w4BrB2bAMdeUd+I2RgloBWALzkBhFLNTlWBdAVOnrUi+uDPIDFaOk8aAX/FI9UHuEQdDQGvHaXyKhm6oUbNfcr4B4cr/UkSvrxdNTCPCK1zfyiyOynyuTY3wkr6vqv1+3jZyWpf0Ns/V5UOj9lDuSeH56q3ipceoIhux2zQAoDz6arlQ0KFTa+xltrUIkhzAFsJPxgsl/LIIG9oKkxZpo38Tf7gG7mXzn1c9G7aPSoY6ih3Gz/2+kRQOrlriBx6fdbLOe6GjE=
  - secure: Kbs37igP4WWWY2mkbxqmftm5Y9goJsH36JNseWX5YP9OropwGHmzpdjSs1fxfLx80XTVdIkmEO9qGiooSgkDp6gbiusHoeQNpl84Zz3lOQHy0Qq6iLRvfzdaRiik9mn0dx92AXwCUoTnLKs/D3KF5tcKqK2fmfYcQOY3eFPqBRosYRrnzk4cKAJnBjildOhw67Mq4Pgu24eos6QXi0UUkps2tjB/BsUSOoIgnW1/W3S46q7dB6pQVgvlHHeWvkPBoa39FA1uUvCQcFxSg06fX6tSy+eUvMi4nAbQ6J5B2kMdnTjgec2FPpyrxOicwQlvRRlA1m8WI04ChbykHE/DjADyv6LabMXVGL4t++1ZnYLdeXR+e2/TJmzW9l4Q0ad1oSNP2fKS5T+XWcW1NnfDns+Y5D2fUL/kNeyA4Xx9fRwhPnRWI/ZG4LbD4y+NKWzMyt/moHUJqRKfS+kEGDw8ckkO3hCa7wQn5KK8WP2uDqx6/mypL6lUfcWSvib6GXfoq5PbZBHEAuEXrVxoEclsR9rakgiX0qXMJkZpxnip+S0FkLn8atvnO8HQFTUDRCY3RSwP8B/HW3ODDWJNoIhtUQPnh4dicOifCWJMMJ8Gekpsjt/MiLPpKk2PNtm9oB71bNMCZHVWDhzks5JIy1LfAcT85oyKFLEgi+P/wKpGt1U=
  - secure: WmTt99eOMxdzsy2CktqgefaB8/lMdxkQCT44V3WcSQAKVZJfnursjmI5kLr6nZ4+W6oNP0PM1mjc4aCZp0g8gFvDGTXb3Mhd1h5o1jIH5R2MPTU0Op3Sc+0VXg0mQMTFtdlE93JE/3Y2Nw6Ixlcxav7I5aSsnVgk5Lue4Qted2otRrPzT/neAIZuiDmYHIMAZ3GlppqDncbZC2tp+D5aNOZjXU+4oxeVNH6nTzqxj0E+ica7N1qKDrjAbpQiU+fqv3SO+nOwVZ49oTugfxOnvWuFINZJqncMx8oLLt7Q9RD30WzgBlP86BDryZZw1HGQwIB9CKDgfCODRU3AkMU7A4/AX6iljalPwXVoEnL418lvPWNwSIh9Y1DMLfiYskpM+HV4aqfeyz7LCqLMeaHamWDpvQ8OiFKLkySBFZ/TOd7cJIs20zPVazcoOPoUvovTkRz30KLwjIxgHe4y8UKeegB81A0l5E7v4DNT7REEYvBmD3ApaAdPU6wmDV3WE5HbRzhJ0nD23aHf93QouMYGept2cH7Gr1/cSNoPs6M5jjnqFzZe6AE5Cyjr6l/p2wERgZQ1C6MtuFWLqcnlupjPp51YtQh17Vo8oNAb/3e38OgLVbbGbPw1YtFC8S4qP9KfNozewxk3Oy8byP+lDIeCtZmsrHR3Wj5SC3lcg331Bj4=
